apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-service
  labels:
    appname: springboot-service
spec:
  selector:
    matchLabels:
      appname: springboot-service
  replicas: 1
  template:
    metadata:
      name: springboot-service
      labels:
        appname: springboot-service
    spec:
      containers:
        - name: springboot-service-container
          image: image-registry.openshift-image-registry.svc:5000/default/springboot-service
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8081"
          ports:
            - name: port1
              containerPort: 8081
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi

---
apiVersion: v1
kind: Service
metadata:
  name: svc-springboot-service
spec:
  type: ClusterIP
  selector:
    appname: springboot-service
  ports:
    - name: port-springboot-service
      port: 8090
      targetPort: 8081

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: ing-springboot-service
spec:
  rules:
    - host: springboot-service.apps.cloud-hr.kolon.com
      http:
        paths:
          - path: /
            backend:
              serviceName: svc-springboot-service
              servicePort: 8090
