apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-blue
  labels:
    appname: portal
    color: blue
spec:
  selector:
    matchLabels:
      appname: portal
      color: blue
  replicas: 2
  template:
    metadata:
      name: portal
      labels:
        appname: portal
        color: blue
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
        - name: portal-container
          image: image-registry.openshift-image-registry.svc:5000/hrl/portal
          imagePullPolicy: Always
          ports:
            - name: port1
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: portal-config
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 1024Mi