apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-green
  labels:
    appname: springboot
    color: green
spec:
  selector:
    matchLabels:
      appname: springboot
      color: green
  replicas: 1
  template:
    metadata:
      name: springboot
      labels:
        appname: springboot
        color: green
    spec:
      nodeSelector:
        node-role.kubernetes.io/worker: ""
      containers:
        - name: springboot-container
          image: quay.io/kako1/springboot
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "8080"
          ports:
            - name: port1
              containerPort: 8080
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1024Mi