apiVersion: v1
kind: Service
metadata:
  name: springboot-svc-test
spec:
  type: ClusterIP
  selector:
    appname: springboot
    color: green
  ports:
    - name: springboot-port
      port: 80
      targetPort: 8080