apiVersion: v1
kind: Service
metadata:
  name: springboot-service-svc
spec:
  type: ClusterIP
  selector:
    appname: springboot-service
    color: blue
  ports:
    - name: springboot-service-port
      port: 80
      targetPort: 8080